// XXX: License

#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "zvkns.h"
#include "zvkb.h"
#include "aes-gcm-test.h"
/* This file is auto-generated by `make test-vectors` */
#include "test-vectors/aes-gcm-vectors.h"

#define MIN(a, b)((a) < (b) ? (a) : (b))

typedef union uint128 {
	uint64_t dwords[2];
	uint32_t words[4];
	uint8_t bytes[16];
} uint128;

__attribute__((aligned(16)))
uint8_t buf[1024];

static void
ghash(uint128 *Y, uint128 *X, uint128 *H)
{
	Y->dwords[0] ^= X->dwords[0];
	Y->dwords[1] ^= X->dwords[1];
	zvkb_ghash(&Y->dwords[0], &H->dwords[0]);
}

static void
encrypt_single(uint8_t *out, uint8_t *in, uint8_t *key, int keylen)
{
	if (keylen == 128) {
		zvkns_aes128_encode_vv(out, in, 16, key);
	} else if (keylen == 256) {
		zvkns_aes256_encode_vv(out, in, 16, key);
	}
}

static void
prepare_icb(uint128 *ICB, uint128 *H, const uint8_t *iv, int ivlen)
{
	uint128 X = {};
	uint64_t blen;

	/*
	 * Easy case.
	 * ICB = IV | round_nr
	 * round_nr starts with 1
	 */
	if (ivlen == 12) {
		memcpy(&ICB->words[0], iv, ivlen);
		ICB->words[3] = 0;
		ICB->bytes[15] = 1;
		return;
	}

	ICB->dwords[0] = 0;
	ICB->dwords[1] = 0;
	blen = 8 * ivlen;

	/* First apply GHASH to full, 128 bit blocks of IV. */
	while (ivlen >= 16) {
		memcpy(&X, iv, 16);
		ghash(ICB, &X, H);
		iv += 16;
		ivlen -= 16;
	}

	/* For a tail block append zeroes and run GHASH. */
	if (ivlen > 0) {
		bzero(&X, sizeof(X));
		memcpy(&X, iv, ivlen);
		ghash(ICB, &X, H);
	}

	X.dwords[0] = 0;
	X.dwords[1] = __builtin_bswap64(blen);
	ghash(ICB, &X, H);
}

static int
run_test(struct aes_gcm_test *test, int keylen)
{
	uint128 H, temp = {}, Y = {}, ICB = {};
	uint128 tag;
	uint8_t *xordata;
	uint32_t counter;
	int rc, rem;

	assert(keylen == 128 || keylen == 256);

	/* H = ENC(0, K)
	 * Borrow a zero 128bit block from ICB.
	 */
	encrypt_single(&H.bytes[0], &ICB.bytes[0], test->key, keylen);
	zvkb_ghash_init(&H.dwords[0]);

	prepare_icb(&ICB, &H, test->iv, test->ivlen);

	if (test->encrypt)
		xordata = test->pt;
	else
		xordata = test->ct;

	/*
	 * Copy initial ICB, it'll later be used to construct
	 * the authentication tag.
	 * The actual ICB used in cipher needs to have the counter
	 * incremented because of that.
	 */
	tag = ICB;
	counter = __builtin_bswap32(ICB.words[3]);
	ICB.words[3] = __builtin_bswap32(++counter);

	for (int i = 0; i < test->aadlen / 16; i++)
		ghash(&Y, (uint128 *)(&test->aad[16 * i]), &H);

	rem = test->aadlen % 16;
	if (rem != 0) {
		bzero(&temp, sizeof(temp));
		memcpy(&temp, &test->aad[test->aadlen - rem], rem);
		ghash(&Y, &temp, &H);
	}

	for (int i = 0; i < test->ctlen / 16; i++) {
		if (!test->encrypt)
			ghash(&Y, (uint128 *)(&xordata[16 * i]), &H);

		encrypt_single(&buf[16 * i], &ICB.bytes[0], test->key, keylen);
		for (int j = 0; j < 16; j++)
			buf[16 * i + j] ^= xordata[16 * i + j];

		if (test->encrypt)
			ghash(&Y, (uint128 *)(&buf[16 * i]), &H);

		ICB.words[3] = __builtin_bswap32(++counter);
	}

	rem = test->ctlen % 16;
	if (rem != 0) {
		if (!test->encrypt) {
			bzero(&temp, sizeof(temp));
			memcpy(&temp, &xordata[test->ctlen - rem], rem);
			ghash(&Y, &temp, &H);
		}

		/* buf shall have enough space to fit the extra bytes. */
		encrypt_single(&buf[test->ctlen - rem], &ICB.bytes[0], test->key, keylen);
		for (int i = 0; i < rem; i++)
			buf[test->ctlen - rem + i] ^= xordata[test->ctlen - rem + i];

		if (test->encrypt) {
			bzero(&temp, sizeof(temp));
			memcpy(&temp, &buf[test->ctlen - rem], rem);
			ghash(&Y, &temp, &H);
		}
	}

	temp.dwords[0] = __builtin_bswap64(8 * test->aadlen);
	temp.dwords[1] = __builtin_bswap64(8 * test->ctlen);
	ghash(&Y, &temp, &H);

	/* Prepare auth tag. */
	encrypt_single(&tag.bytes[0], &tag.bytes[0], test->key, keylen);
	tag.dwords[0] ^= Y.dwords[0];
	tag.dwords[1] ^= Y.dwords[1];

	assert(test->taglen <= sizeof(tag));
	rc = memcmp(&tag, test->tag, test->taglen);
	rc = (!!rc) != test->expect_fail;
	if (rc) {
		printf("\nTag mismatch\n");
		printf("\noutput:   0x");
		for (int i = 0; i < test->taglen; i++) {
			printf("%02x", tag.bytes[i]);
		}
		printf("\nexpected: 0x");
		for (int i = 0; i < test->taglen; i++) {
			printf("%02x", test->tag[i]);
		}
		printf("\n");
		return rc;
	}

	if (test->pt == NULL)
		return 0;

	if (test->encrypt)
		rc = memcmp(buf, test->ct, test->ctlen);
	else
		rc = memcmp(buf, test->pt, test->ctlen);
	if (rc == 0)
		return 0;


	printf("\nText mismatch");
	printf("\ninput:    0x");
	for (int i = 0; i < test->ctlen; i++) {
		if (test->encrypt)
			printf("%02x", test->pt[i]);
		else
			printf("%02x", test->ct[i]);
	}
	printf("\noutput:   0x");
	for (int i = 0; i < test->ctlen; i++) {
		printf("%02x", buf[i]);
	}
	printf("\nexpected: 0x");
	for (int i = 0; i < test->ctlen; i++) {
		if (test->encrypt)
			printf("%02x", test->ct[i]);
		else
			printf("%02x", test->pt[i]);
	}
	printf("\n");

	return rc;
}

int
main()
{
	struct aes_gcm_test *test;
	uint64_t iv;
	int n, rc;

	n = sizeof(gcm_suites) / sizeof(*gcm_suites);

	for (int i = 0; i < n; i++) {
		if (gcm_suites[i].keylen != 128 &&
		    gcm_suites[i].keylen != 256) {
			printf("Skipping test suite %s with unsupported keylen %d\n",
			    gcm_suites[i].name, gcm_suites[i].keylen);
			continue;
		}

		test = gcm_suites[i].tests;
		printf("Running %s test suite... ", gcm_suites[i].name);

		for (int j = 0; j < gcm_suites[i].count; j++, test++) {
			rc = run_test(test, gcm_suites[i].keylen);
			if (rc != 0) {
				printf("test %d failed\n", j);
				exit(1);
			}
		}

		printf("success, %d tests run.\n", gcm_suites[i].count);
	}
	return 0;
}
